//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClientConsoleApp.ExposedSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISrvData", Namespace="http://tempuri.org/")]
    public partial class SrvData : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPeopleOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPersona2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFirstProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFirstCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOneFirstNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerFirstNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEchoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SrvData() {
            this.Url = global::ClientConsoleApp.Properties.Settings.Default.ClientConsoleApp_ExposedSrv_SrvData;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPeopleCompletedEventHandler GetPeopleCompleted;
        
        /// <remarks/>
        public event addPersonaCompletedEventHandler addPersonaCompleted;
        
        /// <remarks/>
        public event addPersona2CompletedEventHandler addPersona2Completed;
        
        /// <remarks/>
        public event GetFirstProductCompletedEventHandler GetFirstProductCompleted;
        
        /// <remarks/>
        public event GetFirstCustomerCompletedEventHandler GetFirstCustomerCompleted;
        
        /// <remarks/>
        public event GetAllCustomersCompletedEventHandler GetAllCustomersCompleted;
        
        /// <remarks/>
        public event GetOneFirstNameCompletedEventHandler GetOneFirstNameCompleted;
        
        /// <remarks/>
        public event GetCustomerFirstNamesCompletedEventHandler GetCustomerFirstNamesCompleted;
        
        /// <remarks/>
        public event GetEchoCompletedEventHandler GetEchoCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/GetPeople", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Persone[] GetPeople() {
            object[] results = this.Invoke("GetPeople", new object[0]);
            return ((Persone[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPeopleAsync() {
            this.GetPeopleAsync(null);
        }
        
        /// <remarks/>
        public void GetPeopleAsync(object userState) {
            if ((this.GetPeopleOperationCompleted == null)) {
                this.GetPeopleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPeopleOperationCompleted);
            }
            this.InvokeAsync("GetPeople", new object[0], this.GetPeopleOperationCompleted, userState);
        }
        
        private void OnGetPeopleOperationCompleted(object arg) {
            if ((this.GetPeopleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPeopleCompleted(this, new GetPeopleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/addPersona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addPersona(Persone p) {
            object[] results = this.Invoke("addPersona", new object[] {
                        p});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addPersonaAsync(Persone p) {
            this.addPersonaAsync(p, null);
        }
        
        /// <remarks/>
        public void addPersonaAsync(Persone p, object userState) {
            if ((this.addPersonaOperationCompleted == null)) {
                this.addPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPersonaOperationCompleted);
            }
            this.InvokeAsync("addPersona", new object[] {
                        p}, this.addPersonaOperationCompleted, userState);
        }
        
        private void OnaddPersonaOperationCompleted(object arg) {
            if ((this.addPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPersonaCompleted(this, new addPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/addPersona2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addPersona2(Persone p) {
            object[] results = this.Invoke("addPersona2", new object[] {
                        p});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addPersona2Async(Persone p) {
            this.addPersona2Async(p, null);
        }
        
        /// <remarks/>
        public void addPersona2Async(Persone p, object userState) {
            if ((this.addPersona2OperationCompleted == null)) {
                this.addPersona2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPersona2OperationCompleted);
            }
            this.InvokeAsync("addPersona2", new object[] {
                        p}, this.addPersona2OperationCompleted, userState);
        }
        
        private void OnaddPersona2OperationCompleted(object arg) {
            if ((this.addPersona2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPersona2Completed(this, new addPersona2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/GetFirstProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsProduct GetFirstProduct() {
            object[] results = this.Invoke("GetFirstProduct", new object[0]);
            return ((clsProduct)(results[0]));
        }
        
        /// <remarks/>
        public void GetFirstProductAsync() {
            this.GetFirstProductAsync(null);
        }
        
        /// <remarks/>
        public void GetFirstProductAsync(object userState) {
            if ((this.GetFirstProductOperationCompleted == null)) {
                this.GetFirstProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFirstProductOperationCompleted);
            }
            this.InvokeAsync("GetFirstProduct", new object[0], this.GetFirstProductOperationCompleted, userState);
        }
        
        private void OnGetFirstProductOperationCompleted(object arg) {
            if ((this.GetFirstProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFirstProductCompleted(this, new GetFirstProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/GetFirstCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsCustomer GetFirstCustomer() {
            object[] results = this.Invoke("GetFirstCustomer", new object[0]);
            return ((clsCustomer)(results[0]));
        }
        
        /// <remarks/>
        public void GetFirstCustomerAsync() {
            this.GetFirstCustomerAsync(null);
        }
        
        /// <remarks/>
        public void GetFirstCustomerAsync(object userState) {
            if ((this.GetFirstCustomerOperationCompleted == null)) {
                this.GetFirstCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFirstCustomerOperationCompleted);
            }
            this.InvokeAsync("GetFirstCustomer", new object[0], this.GetFirstCustomerOperationCompleted, userState);
        }
        
        private void OnGetFirstCustomerOperationCompleted(object arg) {
            if ((this.GetFirstCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFirstCustomerCompleted(this, new GetFirstCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/GetAllCustomers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsCustomer[] GetAllCustomers() {
            object[] results = this.Invoke("GetAllCustomers", new object[0]);
            return ((clsCustomer[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCustomersAsync() {
            this.GetAllCustomersAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCustomersAsync(object userState) {
            if ((this.GetAllCustomersOperationCompleted == null)) {
                this.GetAllCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCustomersOperationCompleted);
            }
            this.InvokeAsync("GetAllCustomers", new object[0], this.GetAllCustomersOperationCompleted, userState);
        }
        
        private void OnGetAllCustomersOperationCompleted(object arg) {
            if ((this.GetAllCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCustomersCompleted(this, new GetAllCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/GetOneFirstName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOneFirstName() {
            object[] results = this.Invoke("GetOneFirstName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneFirstNameAsync() {
            this.GetOneFirstNameAsync(null);
        }
        
        /// <remarks/>
        public void GetOneFirstNameAsync(object userState) {
            if ((this.GetOneFirstNameOperationCompleted == null)) {
                this.GetOneFirstNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneFirstNameOperationCompleted);
            }
            this.InvokeAsync("GetOneFirstName", new object[0], this.GetOneFirstNameOperationCompleted, userState);
        }
        
        private void OnGetOneFirstNameOperationCompleted(object arg) {
            if ((this.GetOneFirstNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneFirstNameCompleted(this, new GetOneFirstNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/GetCustomerFirstNames", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCustomerFirstNames() {
            object[] results = this.Invoke("GetCustomerFirstNames", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerFirstNamesAsync() {
            this.GetCustomerFirstNamesAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomerFirstNamesAsync(object userState) {
            if ((this.GetCustomerFirstNamesOperationCompleted == null)) {
                this.GetCustomerFirstNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerFirstNamesOperationCompleted);
            }
            this.InvokeAsync("GetCustomerFirstNames", new object[0], this.GetCustomerFirstNamesOperationCompleted, userState);
        }
        
        private void OnGetCustomerFirstNamesOperationCompleted(object arg) {
            if ((this.GetCustomerFirstNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerFirstNamesCompleted(this, new GetCustomerFirstNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/GetEcho", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEcho(string pWord) {
            object[] results = this.Invoke("GetEcho", new object[] {
                        pWord});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEchoAsync(string pWord) {
            this.GetEchoAsync(pWord, null);
        }
        
        /// <remarks/>
        public void GetEchoAsync(string pWord, object userState) {
            if ((this.GetEchoOperationCompleted == null)) {
                this.GetEchoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEchoOperationCompleted);
            }
            this.InvokeAsync("GetEcho", new object[] {
                        pWord}, this.GetEchoOperationCompleted, userState);
        }
        
        private void OnGetEchoOperationCompleted(object arg) {
            if ((this.GetEchoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEchoCompleted(this, new GetEchoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetData(int value) {
            object[] results = this.Invoke("GetData", new object[] {
                        value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value) {
            this.GetDataAsync(value, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISrvData/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CompositeType GetDataUsingDataContract(CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persone {
        
        private int idField;
        
        private string nameField;
        
        private string surnameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsCustomer {
        
        private int customerIDField;
        
        private bool nameStyleField;
        
        private string titleField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string suffixField;
        
        private string companyNameField;
        
        private string salesPersonField;
        
        private string emailAddressField;
        
        private string phoneField;
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public bool NameStyle {
            get {
                return this.nameStyleField;
            }
            set {
                this.nameStyleField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string SalesPerson {
            get {
                return this.salesPersonField;
            }
            set {
                this.salesPersonField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsProduct {
        
        private int productIDField;
        
        private string nameField;
        
        private string productNumberField;
        
        private string colorField;
        
        private decimal standardCostField;
        
        private decimal listPriceField;
        
        private string sizeField;
        
        private System.Nullable<decimal> weightField;
        
        private System.Nullable<int> productCategoryIDField;
        
        private System.Nullable<int> productModelIDField;
        
        private System.DateTime sellStartDateField;
        
        private System.Nullable<System.DateTime> sellEndDateField;
        
        private System.Nullable<System.DateTime> discontinuedDateField;
        
        private byte[] thumbNailPhotoField;
        
        private string thumbnailPhotoFileNameField;
        
        private System.Guid rowguidField;
        
        private System.DateTime modifiedDateField;
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ProductNumber {
            get {
                return this.productNumberField;
            }
            set {
                this.productNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public decimal StandardCost {
            get {
                return this.standardCostField;
            }
            set {
                this.standardCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal ListPrice {
            get {
                return this.listPriceField;
            }
            set {
                this.listPriceField = value;
            }
        }
        
        /// <remarks/>
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProductCategoryID {
            get {
                return this.productCategoryIDField;
            }
            set {
                this.productCategoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProductModelID {
            get {
                return this.productModelIDField;
            }
            set {
                this.productModelIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SellStartDate {
            get {
                return this.sellStartDateField;
            }
            set {
                this.sellStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SellEndDate {
            get {
                return this.sellEndDateField;
            }
            set {
                this.sellEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DiscontinuedDate {
            get {
                return this.discontinuedDateField;
            }
            set {
                this.discontinuedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ThumbNailPhoto {
            get {
                return this.thumbNailPhotoField;
            }
            set {
                this.thumbNailPhotoField = value;
            }
        }
        
        /// <remarks/>
        public string ThumbnailPhotoFileName {
            get {
                return this.thumbnailPhotoFileNameField;
            }
            set {
                this.thumbnailPhotoFileNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                this.rowguidField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetPeopleCompletedEventHandler(object sender, GetPeopleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPeopleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPeopleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Persone[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Persone[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void addPersonaCompletedEventHandler(object sender, addPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void addPersona2CompletedEventHandler(object sender, addPersona2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addPersona2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addPersona2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetFirstProductCompletedEventHandler(object sender, GetFirstProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFirstProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFirstProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsProduct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsProduct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetFirstCustomerCompletedEventHandler(object sender, GetFirstCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFirstCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFirstCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsCustomer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsCustomer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetAllCustomersCompletedEventHandler(object sender, GetAllCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsCustomer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsCustomer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetOneFirstNameCompletedEventHandler(object sender, GetOneFirstNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneFirstNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneFirstNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetCustomerFirstNamesCompletedEventHandler(object sender, GetCustomerFirstNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerFirstNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerFirstNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetEchoCompletedEventHandler(object sender, GetEchoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEchoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEchoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591